version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: devsu
      POSTGRES_USER: devsu
      POSTGRES_PASSWORD: devsu
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devsu -d devsu"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: "5432"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "python manage.py migrate --noinput && gunicorn demo.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 4 --log-file -"

volumes:
  pgdata:
