version: '3.9'
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app:cached
    command: gunicorn demo.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 4 --log-file -
