sonar.projectKey=devsu-demo-python
sonar.projectName=Demo Devops Python
sonar.projectVersion=1.0
sonar.sources=api,demo
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.coverageReportPaths=coverage.xml
sonar.python.coverage.reportPaths=coverage.xml
