apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devsu-demo-python
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - middleware-redirect.yaml
  - resourcequota.yaml
  - tls-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: devsu-demo-python
