apiVersion: v1
kind: ResourceQuota
metadata:
  name: devsu-demo-python-quota
spec:
  hard:
    requests.cpu: "900m"
    requests.memory: 700Mi
    limits.cpu: "900m"
    limits.memory: 1Gi
    pods: "5"
    services: "5"
