apiVersion: v1
kind: ResourceQuota
metadata:
  name: devsu-demo-python-quota
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "3"
    limits.memory: 3Gi
    pods: "12"
    services: "5"