apiVersion: v1
kind: Secret
metadata:
  name: devsu-demo-python-secret
type: Opaque
stringData:
  DJANGO_SECRET_KEY: BAUjRUMVyAZPsLUhPuMOegCHVGF9ubaL5DrM8MKcWeX8G5K0Uu
  DATABASE_PASSWORD: ee3e2915f09ff116f6828131210d5bc0e107be8ffb344bd1
