apiVersion: v1
kind: Secret
metadata:
  name: devsu-demo-python-tls
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDNDCCAhygAwIBAgIUDA8lesfDkLf5NN+6LSS4p+hjRuUwDQYJKoZIhvcNAQEL
    BQAwGzEZMBcGA1UEAwwQZGV2c3UtZGVtby5sb2NhbDAeFw0yNjA2MzAwNTA0NDha
    Fw0yNzA2MzAwNTA0NDhaMBsxGTAXBgNVBAMMEGRldnN1LWRlbW8ubG9jYWwwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCmNYDnYJyxTSzuq7OM9T2UT5tf
    t3OMj7BfnrDPyIB9yelzzjHpDATd4Qd9GG3PDqMEfhIs0zHrGzSvxuO0KZ/S5M09
    Rks4QT4sLNy7k4phDIFF3Cdvk4wHCnyQ8L2FvReGO7FSRdbAmCDagpE/zUFhseMW
    vEYgCvAwsoe3PlQ/KmmQmkY8EpJJ5huNomB4rWcLKTNeqqJgXhX/zQLM0vqprpwk
    BtNg8rBgMUTxYDdNX3UxMKnxNyNdS31S7wpxMkCWu7uLE9qTcbHn/KvCHK8uD4CN
    Wbbq99PMPcQVrC3mSokj8pXJQicjCmqsi5qJor8EeUtOat/vEePWIzpCyjx9AgMB
    AAGjcDBuMB0GA1UdDgQWBBQUJwtUyxNErXoJTDKROD90Qt+6SDAfBgNVHSMEGDAW
    gBQUJwtUyxNErXoJTDKROD90Qt+6SDAPBgNVHRMBAf8EBTADAQH/MBsGA1UdEQQU
    MBKCEGRldnN1LWRlbW8ubG9jYWwwDQYJKoZIhvcNAQELBQADggEBACdZpO2qrkQG
    LyG4oxoSnktjXAhBce4D/xAsVTrk36LQh6Ps6ktu/clC1ulQMTuprNr5AjgzsNtT
    2iugaz5BJ5iRfgkYed/jDI+QxxI8nP9yrGdOV8yq5X3QCIxpDS3u31abjBmF4ynh
    jGV1fdQ4LokvyZonPyhhEJPhqqdBazrHXd45rqQga0VweZ4ZK2IZ+1PNlnUAd/jk
    HTfpK0dRh+kTGM5yx+RPYPzQRDTMaTLAT4BL0kqukige5zS9iHcOcLShpvASfYHy
    x5e5IVyVKgDMZ8RRHXxm5v8i5PLLIpfQjL+iHuNxYLoNLPunL32+HsU2nLIfM6Fk
    obyq6oOORXM=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCmNYDnYJyxTSzu
    q7OM9T2UT5tft3OMj7BfnrDPyIB9yelzzjHpDATd4Qd9GG3PDqMEfhIs0zHrGzSv
    xuO0KZ/S5M09Rks4QT4sLNy7k4phDIFF3Cdvk4wHCnyQ8L2FvReGO7FSRdbAmCDa
    gpE/zUFhseMWvEYgCvAwsoe3PlQ/KmmQmkY8EpJJ5huNomB4rWcLKTNeqqJgXhX/
    zQLM0vqprpwkBtNg8rBgMUTxYDdNX3UxMKnxNyNdS31S7wpxMkCWu7uLE9qTcbHn
    /KvCHK8uD4CNWbbq99PMPcQVrC3mSokj8pXJQicjCmqsi5qJor8EeUtOat/vEePW
    IzpCyjx9AgMBAAECggEAGlKA3qPbTO0G/6lrnxg7r2BIIAmCoDElYo9UOyPqzYEL
    ms598wV3Q9hegj47Lb6IrK52nGi6EBzX5DqgVyj8ab7YjiqywO78NKzKLF66XJJJ
    atHp4O7CD19myOGHckW3EwgjFf9/ejLdiR2CeVM9VoaAi1o31N1Gmr+7ZJbXasVA
    OSW+KnV+fmtHRhVhFu0udbc1HfDLw+0qPi7D4Omyj6g0ypUrv5uRVPNu5yJBWl3N
    iOeNW+09vI5zYhTdHWGjjg9F3eL/t+PG+U4FRty4h7p6ZQ/QLy7ruXZ6ds/CR7gA
    OOpeXTzEjAhdVeJhm9h0HzDk4AOkkcbhnE9dY0ZXlQKBgQDew9gl2q5UdDxlX3zk
    mF7JSw8T5gOM+a9IkiKcK26nglaE/ekeQ2xHzFHU5XoFyizB01+1eB50tmDxI0v4
    6wZe7sjfOYVAt3N9/k7B+WpBo6XdiHdGfOy9SufLqq9zfdwMJJlUWYNmdA78NV0T
    XGDeQRjOCddNWeqZgswcyw6nEwKBgQC/AZeL8Lq4BzI9tOBRhL5EGFAegXXVn6+Q
    GiYrV+AbkwNtrfkL/djdoDYQwDj1MNZOqmyV+AiI61UzjQm4WniEjWnF983A7odr
    KSrtPW/4XrSqToFG5M25I1TvreX8Dg0pL+ysLCjE21tlCY1N37us7PyX+4exuXMT
    r/u87+IwLwKBgHQST7nJrDRNLHsVuhnSWvE/rueLXiZCo1aI7oe5Cbs2aqZ5NtKS
    BwWSLMFloKMLqS6FWMVRhW0C6pg68AcPTw6AFSJa8le6Pu9TZu4ja34wKui3ho6v
    4RrwwL6afTkMR2/8Ufhle9YSewxnMcw4wjCMcsRI1Gp1g4vhX0FRfJ0JAoGAawIN
    UQ0wzmDZuNBYy9K+dY/Zcv28ck3gIa9Eqwu0Nj6KsSvCVwGEOcXEBGZsgpE1vySj
    aPFodqzBMvxU8b9dvYUsOQi3cNsxasvJjNfanx8PwEnzCzCsQIiW0SBvtGJ65RRA
    V8T1ojPyZAyR6YrqrdqnOM5mGx92ZRU2x4btBWkCgYAc3y6o3OcuzyZMcoeD4nKT
    vlhIOOaY5v5e6pivWrp7pm2shWVYUUD0CxKkr2nhm+OQxC7cn8S861OQ37xkv8AV
    O98csuFI2BELhH+13eJflA0WyYUC7Z0cW7HRhg+TtxpbLX5pDB644LSalsObMz6W
    WjM4SPA7nzBICrKx3j6kSA==
    -----END PRIVATE KEY-----
