apiVersion: v1
kind: Secret
metadata:
  name: devsu-demo-python-tls
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDOjCCAiKgAwIBAgIUbTooO7hkNYBzZEFEy0YH7VNxvVEwDQYJKoZIhvcNAQEL
    BQAwHTEbMBkGA1UEAwwSYXBpLnBsdXNjbG91ZGl0LnBlMB4XDTI2MDYzMDA3NTUw
    NVoXDTI3MDYzMDA3NTUwNVowHTEbMBkGA1UEAwwSYXBpLnBsdXNjbG91ZGl0LnBl
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt+IJQPm/QOQP5qlGUlbQ
    BCgjDssSn8Fjv3ZChVSKtCCZoiH/hA4EBMEJE193T170ZxDK01pZZIFytah07M8m
    vtWHwAglCAk16lQw3cB0trbz+0Dk942tMk06M/3jn9ycP6edo+VISqhqgb5FR8s/
    N0qnRkydW+cAgx8XEHpnZDUPM4LG7YeR6GbvFDO3umipJWIGIi9c5VN6Bmxml3z4
    6RDHlddmA2DKNDNUo96igtjCzFtdYk9M7YkPci+z2aFz42ZQmwNqGL1iv5uvTjSc
    yXrd+pFTe1ZO4smwXHP15Sa69rs+ysZK+1eXzFsaAUvh82Q3WSjRP1hAoXAlpbX0
    4wIDAQABo3IwcDAdBgNVHQ4EFgQUaww/koI2sD4l4LRP5JV0U+Uk9ZkwHwYDVR0j
    BBgwFoAUaww/koI2sD4l4LRP5JV0U+Uk9ZkwDwYDVR0TAQH/BAUwAwEB/zAdBgNV
    HREEFjAUghJhcGkucGx1c2Nsb3VkaXQucGUwDQYJKoZIhvcNAQELBQADggEBABOF
    x0aGfcovKhi+JELLsuBz+EGL0fpf87jixq/va1sl+4KOKKqtEPkBnR8lRAHDG0sM
    +JpiOcb5JMeYHLkvmL6suUKeFXnuoXzl6gQVb7VV/Rkj8Xgdycoki9OG4yWPq1Oo
    oc6gSkIBnckkKW69lCx5/tE58Lu9xBt7m2S02+FXRF6FQMr6JmdkyNlu3TT7IMij
    cgOGqlcCJzttQVqREFpcmpR2KYeE2pW8KMXvs0QgXDOjxaD1GMPWk8z6BPG1XpjR
    eak6cT6eBy20UcEnoxVsVPP/SV/4Ek/1zou5acfezAAe//2O4qIQW3Y2CWPhb61O
    qPlsvZJjnir6WoLUiF0=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC34glA+b9A5A/m
    qUZSVtAEKCMOyxKfwWO/dkKFVIq0IJmiIf+EDgQEwQkTX3dPXvRnEMrTWllkgXK1
    qHTszya+1YfACCUICTXqVDDdwHS2tvP7QOT3ja0yTToz/eOf3Jw/p52j5UhKqGqB
    vkVHyz83SqdGTJ1b5wCDHxcQemdkNQ8zgsbth5HoZu8UM7e6aKklYgYiL1zlU3oG
    bGaXfPjpEMeV12YDYMo0M1Sj3qKC2MLMW11iT0ztiQ9yL7PZoXPjZlCbA2oYvWK/
    m69ONJzJet36kVN7Vk7iybBcc/XlJrr2uz7Kxkr7V5fMWxoBS+HzZDdZKNE/WECh
    cCWltfTjAgMBAAECggEAHtgSd0ytMQRQSn+gZRVcxSW6Y7PahuOYiLgchmLc9UP2
    oUSUqKD1OZrrm81KpQyncFZXv0YLcploFWKRYluJAz+sCqETHRr2aT0ACWJL8Y4U
    tNN41LF2GNbtaWUv9lO5/c9u2NwP2T4Qx3yUAGvuSacDEf6t8ol4A4aGhuQRTbRz
    tCtNiwz2p43u0oYuCuqcmNPva1FFLb2Wa4xMj8VJa7oehQ4h6YwZCEE1NHg01bXC
    6/UWES4a7qWs7S8tRosSpp1eolhdWc3GpxWPamXOYdTs/ojtgJk6mS35fzuq34Fg
    cVFl2+zPtbkgv1CHOyfYl5SDy8cfx4XnZZjoJ75vEQKBgQDroxBI9+1ComjfMOoT
    aaRPMDQ9aMrRHpJH5VwIfMyVvBaal5ydR+5CXnb2pBh/xRvNcSjarcRVM92j7jb5
    q0O3NzbK1pGIJ3fyitNKKyIM8mQv3vQkVQVhyghtNfJtDbCl3RkiN296SXGs8cLP
    4UYNn19sG3+ehLCUifid5TFZ6wKBgQDHxggfB/cAPyfOz9G4mMHBKGwefIDIQP8X
    Ir9HHimSQ0YuOSe8U9FMJAXgEUzG94Yf9Kl8b0gbRJDP70c4CJXs4pW5zGLMoWRa
    gWTURCK6guuUM44vplWCXECPP9DTf1vQtjL6tTrs3EMOfy9R4x/BGyXmaR4KxqHU
    NFYeUGva6QKBgHfepPspvHXIXucjYABuHlr2X6zZsUs+bRXL9MyQiBan7yvHcrGE
    FQ2INqZzhc8Bu4oARdMw0I6zas3o8eiCmlkK6oG3M6N6yIcG3kN9u72wVQ0RM0uE
    QM+lUjIUXnXhn/pQhmekob4ovH5JIlxT8iod6BH7zykZwSZfJa1VGYzvAoGBAL0I
    2Jp0cPecy1BZOjwQ4Bak51oZucrEJh2AVbs4AWJTok8O6li8f2orFBwogpwrkJEg
    dFg4/ORAhz8bTirphOS4q7E6g6radRlnIz/wkWQnij+cYUkZfgRywuxKGJJpCzp9
    jdPKNc33xsQq+V3lKyERTVWv1iugNXWVaIAa3VQxAoGBAMt7Wt7IsJ+rVHmJf6s5
    NxSo+fYb2rZvZI3rGxPDMhEdgUzugOPZs5qmQwOPf7dKlr6cj01UdQvqfFuNy6pr
    WpLWDCrU76IOdpy2Gd8TlqqNlI8lXLRWSJnLEA1KIGzrfRVtYRH3HiPWEvQR9/ZF
    ajKymMlyquVdiSBHx/WpL/19
    -----END PRIVATE KEY-----
